### ISSUE TITLE
Can't add User Groups

### ISSUE THREAD

**Issue by omranjamal** [php-ug/php.ug#130]
I'm from dhaka,bangladesh. So I thought of adding the user group I'm a part of to phpug, but theres always an error with the location saying "The given longitude exceeds the range of -180 to 180 degrees".

![Screenshot](http://i.imgur.com/gAcWCkA.jpg)

**Comment by heiglandreas** [comment]
Ah, That can happen when you "rotate" the map too far. To get you set up, ping me via the contact-form or via email with the details and I'll get you set up.

Besides that I'll have to adapt the validation to also allow different values and then reduce them to appropriate values.

**Comment by heiglandreas** [comment]
Hey @omranjamal - Sorry for not following up on this one! Have you tried adding the group again? Can you give me more informations on the group? I'd love to get you up and running

**Comment by heiglandreas** [comment]
As there was no response, I'll close this now…
