### ISSUE TITLE
Filter Calendar by Country

### ISSUE THREAD

**Issue by gabrielsomoza** [php-ug/php.ug#131]
This would be useful especially for meetup organizers, e.g. so we can subscribe to an iCal feed that only shows activity in our region (in my case Benelux). 

The problem right now is that if you subscribe you basically spam your calendar with remote events that you don't care about.

This could be related to or combined with https://github.com/php-ug/php.ug/issues/127

If anyone else finds this interesting/useful I can work on a PR.

**Comment by gabrielsomoza** [comment]
@mikesimonson, @wimg

**Comment by heiglandreas** [comment]
I'd be absolutely pleased to see a PR :wink:

**Comment by heiglandreas** [comment]
@gabrielsomoza I've just updated http://php.ug so that you can now subscribe a calendar that only contains events from usergroups within a certain radius around a geolocation. You can use ```http://php.ug/api/v1/calendar/list?latitude=<your latitude>&longitude=<your longitude>&distance=<max distance from your location>&count=<consider only he nearest n usergroups from your location>```

You can ommit ```count``` or ```distance``` depending on your needs

Does that help you in a way?

**Comment by gabrielsomoza** [comment]
Yes, it does! What's he unit of distance?

**Comment by heiglandreas** [comment]
Unit of distance is kilometers

**Comment by gabrielsomoza** [comment]
Thanks!
