### ISSUE TITLE
Mentors can not be displayed

### ISSUE THREAD

**Issue by tdutrion** [php-ug/php.ug#177]
The mentors page of the website does not provide mentors pins any more.

`Uncaught TypeError: Cannot read property 'length' of undefined`

`for(var i = 0; i< e.apprentices.length; i++) {`

A problem seems to be happening with fetching the data. I have no more time today to investigate more, but basically [https://github.com/phpmentoring/phpmentoring.github.com/wiki/Mentors-and-Apprentices](https://github.com/phpmentoring/phpmentoring.github.com/wiki/Mentors-and-Apprentices) does not exist anymore ([old version here](https://web.archive.org/web/20150211114157/https://github.com/phpmentoring/phpmentoring.github.com/wiki/Mentors-and-Apprentices)).

**Comment by heiglandreas** [comment]
Thanks for reporting. As the mentoring-plattform changed their list from the github-page to the app it happened sometimes that the github-page got missing. Therefore I've added the mentoring-app view on the map @ php.ug. 

Until now I didn't remove the "old" mentoring-layer but you are absolutely right that that is irritating.

I'll investigate and fix it ;)

**Comment by heiglandreas** [comment]
Should work now as expected. Can you verify that?

**Comment by tdutrion** [comment]
Works fine indeed, thanks!
