### ISSUE TITLE
Add form to create an invitation to the slack channel

### ISSUE THREAD

**Issue by heiglandreas** [php-ug/php.ug#200]
It would be nice to have a form within the php.ug-website that allows one to enter an email-address to get an invitation to the slack-channel.

That would ease the issue of possibly changing external links to a service that creates an invitation. (See https://github.com/phphants/phph-site/issues/136#issuecomment-261926201)

**Comment by heiglandreas** [comment]
Perhaps as an alternative we could use https://slack.php.ug as shortlink to the slack-channel and https://slack.php.ug/invite as shortlink to an invitation-form

@asgrim Would that solve your issue with possibly changing URLs?

**Comment by asgrim** [comment]
Yes that would be ideal! :) thanks

**Comment by heiglandreas** [comment]
That has already been solved with #201
