### ISSUE TITLE
Correct spelling of TYPO3 according to the Style-Guide

### ISSUE THREAD

**Issue by heiglandreas** [php-ug/php.ug#205]
Thanks to @Avalarion for bringing this to our attention! 

The style-guide can be found at https://typo3.org/about/the-brand/style-guide/the-typo3-spelling/

**Comment by Avalarion** [comment]
Hey ho,

found the SQL file and changed its content. Why is it compressed? That way you are not able to see my changes and the git history is full of binary files...

However. I did the changes and would love you to review them. I have not read how your deployment works, do you need to change this Tag entry in the database manually?

Greetings,

Bastian
