### ISSUE TITLE
PHP.UG Map Redesign Suggestions

### ISSUE THREAD

**Issue by mkorkmaz** [php-ug/php.ug#209]
### Visual

- Custom map colors using new site’s design colors.
- New marker icon (i.e: an elephant or etc).
- Independent marker popup design (in place or fixed place on the map).
- No repeating world maps
- Responsive map

### Functional

- Filter by tags
- Filter by country (Zooms to country and displays only markers related to that country)
- Filter by continent (Zooms to continent and displays only markers related to that continent)
- Filter by keyword (i.e: One may be remember twitter handle of UG and want to search using twitter handle)
- Marker clustering (Clusters are updated automatically by zoom levels and map bounds)
![Preview Map Cluster](https://i.imgur.com/UzkeMaJ.png)

### Data and JS issues
- Additional data can be integrated to API response or can be populated using JS after Ajax response.
- Can be bundled independently using Webpack
- Can be implemented using vanilla js (except map libraries)
- Can be implemented using ReactJS etc. (if new frontend will use ReactJS etc.)
- If ancient browsers can be ignored MapboxGL JS can be used (for extra features including responsive map)

**Comment by heiglandreas** [comment]
Sounds good to me! 

I'm interested in the sites design colors ;)

Apart from that almost all necessary data should be providable by the API at this stage already. Only thing might be the continent. And the backends search-functionality needs improvement. 

I'm not sure how to implement it but I'm absolutely willing to try React a second time. Though we not only need the map but also the promotion form. That's the one I'm having more issues with :wink: 
But using Webpack to bundle all the stuff would be OK for me as well. There's no need to over-engineer. I'd rather see less pages on php.ug and more in the wiki. And I'm thinking about the php.net-wiki here.

So for me the new Website has the following pages:

* / (home, the Map)
* /promote - The form to create new and edit existing usergroups
* /contact - A simple contact form.

All other links IMHO are links to external pages/sites/applications/API-endpoints. The legal stuff would link to a Github-Wiki-page, the Features-entries link to the appropriate API-endpoints and the Tipps & Tricks links to the Usergroup-Entry in the php.net-wiki

There might be some additional pages for the website like 

* https://php.ug/feature/twitternicklist
* https://php.ug/api/v1/calendar/list
* https://php.ug/feature/calendar

But those are more like separate one-page apps that can live somewhere else and are only linked from the php.ug-website…

As interesting as MapGL is, it's still a paid solution and  I'm not willing to include that at this moment as there's no one sustainably funding the project (apart from me :wink:). I'd rather prefer leaflet as it's a free library that is highly extendable using plugins.

**Comment by heiglandreas** [comment]
Please direct further discussions to https://github.com/orgs/php-ug/teams/web-php-ug/discussions

**Comment by mkorkmaz** [comment]
@heiglandreas The link gives 404 to me :)

Here are my further notes:
- If there will be few pages then I can implement client-side using ReactJS.
- I can provide 2-letter country iso code, country name, continent name, GPS locations and zoom level data if it needed for the backend integration.
- Mapbox can use OpenStreetMap tiles, It is kinda commercial version of Leaflet, and we will only use MapboxGL JS library, that's all, nothing to be paid :) If you want to go with MIT/GPL/BSD friendly licenses, then we can go with Leaflet, that is also OkK for me.

**Comment by heiglandreas** [comment]
the 404 was before or after accepting the invitation?
