### ISSUE TITLE
Calling usegroup 1 fails

### ISSUE THREAD

**Issue by TomasVotruba** [php-ug/php.ug#211]
Just try: https://php.ug/api/rest/usergroup/1

```
{"message":"Argument 2 passed to Phpug\\Api\\Rest\\ListtypeController::__construct() must be an instance of Phpug\\Cache\\Cache, instance of Phpug\\Acl\\RoleManager given, called in \/home\/phpug\/php.ug\/src\/module\/Phpug\/src\/Phpug\/Api\/Rest\/UsergroupControllerFactory.php on line 45","type":"TypeError"}
```

Not sure if this is some invalid input on my side. Should be reported in another way though

My goal is to render all events. How to do that? I didn't get it from the api docs. I'd expect command like 

```
https://php.ug/api/rest/events/
```

**Comment by heiglandreas** [comment]
THanks for reporting. I do need to check that!

Meanwhile use http://php.ug/api/rest/listtype.json/1 instead to retrieve informations about the usergroups…

**Comment by heiglandreas** [comment]
Fixed it and it should work now. Though ATM you have to provide the ID of the usergroup.

**Comment by TomasVotruba** [comment]
Thanks for the fix :+1:
