### ISSUE TITLE
[api] How to get list of events?

### ISSUE THREAD

**Issue by TomasVotruba** [php-ug/php.ug#212]
I've read the "[List of usergroup-events](http://php-ug.github.io/php.ug/community/2015/01/01/Calendar-of-usergroup-events/)" post and tried the url:

```php
$client = new GuzzleHttp\Client();
$result = $client->request('GET', 'https://php.ug/api/v1/calendar/list');
```

but that doesn't work.

I looked at http://api.php.ug before (doesn't work now), but all I could found were user groups and their location.

Any ideas?

**Comment by heiglandreas** [comment]
You'll need to add an `Accept: application/json`-header to get something sensible.

Or `Accept: text/calendar` to get an iCalendar-file. Depending on what you want to achieve one or the other is easier to handle…

**Comment by heiglandreas** [comment]
Try something like this:

```php
$client = new GuzzleHttp\Client([
    'headers' => [
        'Accept' => 'application/json'
    ]
]);
$result = $client->get('https://php.ug/api/v1/calendar/list');
```

**Comment by heiglandreas** [comment]
Hm... Good point… the result doesn't have a link to the usergroup - that's definitely optimizable… And with that link to the usergroup you'd be able to get the correct location....

But currently sadly no. There's no easy way to retrieve the location other than parsing the part within the square brackets.

**Comment by TomasVotruba** [comment]
I think the name parsing will be better, cause I need European map as simple as possible.

I know distance math can be really difficult and e.g. Germany is much more clear to me and Google maps.

Good enough for me, thanks :bowing_woman:
