### ISSUE TITLE
Redirecting http to https

### ISSUE THREAD

**Issue by petk** [php-ug/php.ug#218]
Hello, might be a good addition to add redirection from http://php.ug to https://php.ug

Thank you for considering adding this one day as well.

**Comment by TomasVotruba** [comment]
I use Cloudflare for similar projects like these with 5-minutes https setup.
It's not perfect as manual hosting installation, but it's good enought, safer than http and just works.

Here is simple tutorial in 3 steps: https://pehapkari.cz/blog/2017/03/13/how-to-add-https-to-github-pages-in-6-steps/#how-to-enable-https-in-3-steps

**Comment by heiglandreas** [comment]
Implemented. http://php.ug will redirect to https while f.e. http://ffm.php.ug will not. Well, it will redirect to the phpgffm-website but that's expected behaviour. And that there is no redirect to https is something completely different.

**Comment by TomasVotruba** [comment]
Is the redirect active yet? It still stays on http for me
