### ISSUE TITLE
Empty map in Chrome...

### ISSUE THREAD

**Issue by heiglandreas** [php-ug/php.ug#221]
https://files.slack.com/files-pri/T04332UAD-FE2FAD8UF/image.png

I can not reproduce this issue but @TomasVotruba can repeatedly. Would you mind sharing somemore details like f.e.the network-graph? THX

**Comment by TomasVotruba** [comment]
Not sure if related, but both http:// and https:// version are allowed.

There is no redirrect. Which is correct?

![image](https://user-images.githubusercontent.com/924196/48355881-b1150980-e69d-11e8-81f0-7af026489651.png)

![image](https://user-images.githubusercontent.com/924196/48355893-ba05db00-e69d-11e8-8873-b3bb41a96818.png)

**Comment by TomasVotruba** [comment]
Found them :+1: 

![image](https://user-images.githubusercontent.com/924196/48356224-6f389300-e69e-11e8-9c86-9c0ff9b7a0fa.png)

**Comment by heiglandreas** [comment]
https is correct!
