### ISSUE TITLE
GitHub Auth seems to be broken

### ISSUE THREAD

**Issue by Basster** [php-ug/php.ug#225]
I just tried to move from twitter auth to github auth and ran into the following issue:

I've authenticated via GitHub and received the following error:

```json
{"message":"Client error: `GET https:\/\/api.github.com\/user?access_token=<github-token-here>` resulted in a `400 Bad Request` response:\n{\n  \u0022message\u0022: \u0022Must specify access token via Authorization header. https:\/\/developer.github.com\/changes\/2020-02-10-depr (truncated...)\n","type":"GuzzleHttp\\Exception\\ClientException"}
```

But it seems I have a session now, because when I reenter [php.ug](https://php.ug/) I get a blank page with status 500.

```
HTTP/2 500 Internal Server Error
server: nginx/1.14.0 (Ubuntu)
date: Fri, 03 Feb 2023 10:31:08 GMT
content-type: text/html; charset=UTF-8
expires: Thu, 19 Nov 1981 08:52:00 GMT
cache-control: no-store, no-cache, must-revalidate
pragma: no-cache
X-Firefox-Spdy: h2
```

Once I delete my PHPSESSID Cookie, it's all back to normal.

**Comment by heiglandreas** [comment]
WTF.... On it!

**Comment by Basster** [comment]
https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param/

**Comment by heiglandreas** [comment]
Fixed!

The whole application is running in a ... rather deprecated state :see_no_evil: 

Updating that to a current system is on my agenda for quite some years now....

But works for now again.

Thanks for reporting!
