### ISSUE TITLE
Would like to add the Mastodon account of my UG to the site

### ISSUE THREAD

**Issue by shochdoerfer** [php-ug/php.ug#226]
I just logged into the site and tried to add the Mastodon account to my meetup and realized this is not possible yet. Any chance to add this?

**Comment by heiglandreas** [comment]
There might be a slight chance.

Check it out now...

**Comment by heiglandreas** [comment]
You'll have to add the full URL to the account though!

**Comment by shochdoerfer** [comment]
Works. Thanks.
